openapi: 3.0.0
info:
  version: '3.0'
  title: Get Bom Assembly channels API
  license:
    name: MIT
servers:
- url: https://{endpoint}/services/apexrest/{namespace}/v2
  variables:
    endpoint:
      description: This is the Salesforce instance url. It is the URL when using Salesforce Classic, i.e. propel.my.salesforce.com
    namespace:
      default: PDLM
      description: This value should default to PDLM for production environments. For dev environments, provide the namespace to your dev org.
tags:
- name: channels
paths:
  /channels:
    get:
      operationId: getAllChannels
      summary: Get All Channels
      tags:
      - channels
      security:
      - salesforceOAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
              - id: <string>
                name: <string>
                categoryId: <string>
                classification: <string>
                parentId: <string>
                isPrimary: <boolean>
                productList:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
                subcategories:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
              - id: <string>
                name: <string>
                categoryId: <string>
                classification: <string>
                parentId: <string>
                isPrimary: <boolean>
                productList:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
                subcategories:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /channels/{channelId}:
    get:
      operationId: getChannelInfo
      summary: Get Channel Info
      tags:
      - channels
      security:
      - salesforceOAuth: []
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                id: <string>
                name: <string>
                categoryId: <string>
                classification: <string>
                parentId: <string>
                isPrimary: <boolean>
                productList:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
                subcategories:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /channels/{channelId}/products:
    get:
      operationId: getChannelSProducts
      summary: Get Channel's Products
      tags:
      - channels
      security:
      - salesforceOAuth: []
      parameters:
      - name: channelId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
              - id: <string>
                name: <string>
                category:
                  id: <string>
                  name: <string>
                channels:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
                variants:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
                attributes:
                - status: <string>
                  product_weight: <number>
                  battery_size: <string>
                - status: <string>
                  product_weight: <number>
                  battery_size: <string>
                assets:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
              - id: <string>
                name: <string>
                category:
                  id: <string>
                  name: <string>
                channels:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
                variants:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
                attributes:
                - status: <string>
                  product_weight: <number>
                  battery_size: <string>
                - status: <string>
                  product_weight: <number>
                  battery_size: <string>
                assets:
                - id: <string>
                  name: <string>
                - id: <string>
                  name: <string>
        '401':
          description: Unauthorized
        '404':
          description: Not found
